add support for multiple arguments

diff --git a/bin/steal b/bin/steal
--- a/bin/steal
+++ b/bin/steal
@@ -3,11 +3,17 @@
 set -euo pipefail
 
 if [ $# -eq 0 ]; then
-  echo "Usage: $0 <file-path>"
+  echo "Usage: $0 <file-path>..."
   exit 1
 fi
 
-# convert the symlink to a copy of the file
-cp --remove-destination "$(readlink -f $1)" $1
-# set permissions because nix store is readonly
-chmod u+w $1
+for file in "$@"; do
+  if [ ! -e "$file" ]; then
+    echo "Error: '$file' is not a valid file path." >&2
+    continue
+  fi
+  # convert the symlink to a copy of the file
+  cp --remove-destination "$(readlink -f "$file")" "$file"
+  # set permissions because nix store is readonly
+  chmod u+w "$file"
+done
